### ISSUE TITLE
error when getting channel

### ISSUE THREAD

**Issue by synhya1** [SuspiciousLookingOwl/youtubei#104]
code
`
    const channel = await youtube.getChannel(channelId);
    const shorts = channel.shorts;
`

TypeError: Cannot read properties of undefined (reading 'imageBannerViewModel')
    at ChannelParser.loadChannel (C:\Users\somes\OneDrive\바탕 화면\music\shortsmusic_admin\node_modules\.pnpm\youtubei@1.4.2\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:32:34)
    at Channel.load (C:\Users\somes\OneDrive\바탕 화면\music\shortsmusic_admin\node_modules\.pnpm\youtubei@1.4.2\node_modules\youtubei\dist\cjs\youtube\Channel\Channel.js:20:39)
    at Client.<anonymous> (C:\Users\somes\OneDrive\바탕 화면\music\shortsmusic_admin\node_modules\.pnpm\youtubei@1.4.2\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:102:60)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\somes\OneDrive\바탕 화면\music\shortsmusic_admin\node_modules\.pnpm\youtubei@1.4.2\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot destructure property 'shortIds' of '(intermediate value)' as it is undefined.
    at getVideoFromChannel (eval at instantiateModule (file:///C:/Users/somes/OneDrive/%EB%B0%94%ED%83%95%20%ED%99%94%EB%A9%B4/music/shortsmusic_admin/node_modules/.pnpm/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55033:28), <anonymous>:80:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.updateVideoMetadata (eval at instantiateModule (file:///C:/Users/somes/OneDrive/%EB%B0%94%ED%83%95%20%ED%99%94%EB%A9%B4/music/shortsmusic_admin/node_modules/.pnpm/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55033:28), <anonymous>:15:39) 
    at async Module.scheduleUpdateYTVideo (eval at instantiateModule (file:///C:/Users/somes/OneDrive/%EB%B0%94%ED%83%95%20%ED%99%94%EB%A9%B4/music/shortsmusic_admin/node_modules/.pnpm/vite@5.2.10/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:55033:28), <anonymous>:36:7)

**Comment by SuspiciousLookingOwl** [comment]
Can you provide a channel id that throws this error?

**Comment by synhya1** [comment]
TypeError: Cannot read properties of undefined (reading '0')
[1]     at ChannelParser.parseShelves (/app/node_modules/.pnpm/youtubei@1.4.2/node_modules/youtubei/dist/cjs/youtube/Channel/ChannelParser.js:68:34)
[1]     at ChannelParser.loadChannel (/app/node_modules/.pnpm/youtubei@1.4.2/node_modules/youtubei/dist/cjs/youtube/Channel/ChannelParser.js:42:40)
[1]     at Channel.load (/app/node_modules/.pnpm/youtubei@1.4.2/node_modules/youtubei/dist/cjs/youtube/Channel/Channel.js:20:39)
[1]     at Client.<anonymous> (/app/node_modules/.pnpm/youtubei@1.4.2/node_modules/youtubei/dist/cjs/youtube/Client/Client.js:102:60)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/app/node_modules/.pnpm/youtubei@1.4.2/node_modules/youtubei/dist/cjs/youtube/Client/Client.js:5:58)

the error i posted is now not showing up. instaed, i get this error when i get channel from "UC65jMyKQ-YEpcZpAwe7Dbww" here.

    const channel = await youtube.getChannel("UC65jMyKQ-YEpcZpAwe7Dbww");

**Comment by antoniojps** [comment]
This is because the last commit has not been published yet.
