### ISSUE TITLE
error when getting channel (version 1.4.3)

### ISSUE THREAD

**Issue by synhya1** [SuspiciousLookingOwl/youtubei#108]
channelId: "UCJQ4mutu_vUxjbiIZIUc0qg"
code: const channel = await youtube.getChannel(channelId);

TypeError: Cannot read properties of undefined (reading 'contents')
    at ChannelParser.parseShelves (C:\Users\Administrator\Desktop\work\shortsmusic-admin\node_modules\.pnpm\youtubei@1.4.3\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:51:64)
    at ChannelParser.loadChannel (C:\Users\Administrator\Desktop\work\shortsmusic-admin\node_modules\.pnpm\youtubei@1.4.3\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:43:40)
    at Channel.load (C:\Users\Administrator\Desktop\work\shortsmusic-admin\node_modules\.pnpm\youtubei@1.4.3\node_modules\youtubei\dist\cjs\youtube\Channel\Channel.js:20:39)
    at Client.<anonymous> (C:\Users\Administrator\Desktop\work\shortsmusic-admin\node_modules\.pnpm\youtubei@1.4.3\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:102:60)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Administrator\Desktop\work\shortsmusic-admin\node_modules\.pnpm\youtubei@1.4.3\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by SuspiciousLookingOwl** [comment]
Thank you for opening an issue.

Fixed on `1.4.4`

**Comment by synhya1** [comment]
Thanks for quick fix.
