### ISSUE TITLE
type error when there are no subscribers on the channel

### ISSUE THREAD

**Issue by synhya1** [SuspiciousLookingOwl/youtubei#110]
TypeError: Cannot read properties of undefined (reading 'text')
[1]     at ChannelParser.loadChannel (/app/node_modules/.pnpm/youtubei@1.5.3/node_modules/youtubei/dist/cjs/youtube/Channel/ChannelParser.js:31:59)
[1]     at Channel.load (/app/node_modules/.pnpm/youtubei@1.5.3/node_modules/youtubei/dist/cjs/youtube/Channel/Channel.js:20:39)
[1]     at Client.<anonymous> (/app/node_modules/.pnpm/youtubei@1.5.3/node_modules/youtubei/dist/cjs/youtube/Client/Client.js:103:60)
[1]     at Generator.next (<anonymous>)
[1]     at fulfilled (/app/node_modules/.pnpm/youtubei@1.5.3/node_modules/youtubei/dist/cjs/youtube/Client/Client.js:5:58)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

channel : UCrDcyOUWa-vgFdYl36yolZw, UCPlb5wjR21PChUwv6yLm-qw

happens when await youtube.getChannel("UCrDcyOUWa-vgFdYl36yolZw");

thanks always for making nice package

**Comment by SuspiciousLookingOwl** [comment]
Fixed on `1.5.4`. Thank you for reporting the bug!
