### ISSUE TITLE
Youtube.getChannel has stoped working

### ISSUE THREAD

**Issue by MohamedAdany** [SuspiciousLookingOwl/youtubei#111]
**Describe the bug**
Error fetching channel: TypeError: Cannot destructure property 'channelId' of 'data.header.c4TabbedHeaderRenderer' as it is undefined.
    at ChannelParser.loadChannel (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:10:17)
    at Channel.load (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Channel\Channel.js:20:39)
    at Client.<anonymous> (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:98:60)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:5:58)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
runScrapper for UCy9JFar6xrcECNQ0dBw5swg Lipton 
Error fetching channel: TypeError: Cannot destructure property 'channelId' of 'data.header.c4TabbedHeaderRenderer' as it is undefined.
    at ChannelParser.loadChannel (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:10:17)
    at Channel.load (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Channel\Channel.js:20:39)
    at Client.<anonymous> (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:98:60)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ADMIN\Desktop\ALPHALOGIX\youtube-fullstack\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:5:58)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**To Reproduce**
      const channel = await youtube.getChannel(channelId);

**Expected behavior**
I am expecting to get channel info ,which I was using further to fetch all videos of channel,it was working fine initially, then started getting this error on getChannel call.please help and let me know how i can fix this asap
**

**Comment by SuspiciousLookingOwl** [comment]
Hi, which version of `youtubei` are you using? It seems like you are still using the older version (`>= 1.4.1`), which has a broken channel parser.

This code works fine for me on the latest version (`1.5.3`)

```ts
const client = new Client()
const channel = await client.getChannel("UCy9JFar6xrcECNQ0dBw5swg");
```

**Comment by MohamedAdany** [comment]
hello, thanks for responding, ok i just checked and got to know I was using     "youtubei": "^1.2.0",updated package and it is working now :)

**Comment by MohamedAdany** [comment]
issue resolved, closing it
