### ISSUE TITLE
"Cannot read properties of undefined (reading 'videoId')" in nodejs lambda environment.

### ISSUE THREAD

**Issue by jo-sip** [SuspiciousLookingOwl/youtubei#124]
**Describe the bug**
I'm running into an issue where supplying a valid videoId throws a stack trace when running in a lambda environment. This happens:

TypeError: Cannot read properties of undefined (reading 'videoId')
    at BaseVideoParser.loadBaseVideo (/var/task/index.js:79129:44)
    at Video.load (/var/task/index.js:79289:43)
    at Video.load (/var/task/index.js:80595:15)
    at Client3.<anonymous> (/var/task/index.js:80753:113)
    at Generator.next (<anonymous>)
    at fulfilled (/var/task/index.js:80655:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

when the videoId is defined.

Could there be some async client issue? Static loadBaseVideo member? **parseRawData returning null or no data**? I'm thinking the latter could be likely, are there some options I need to set for different environments?

```
const youtube = new Client();
```

**To Reproduce**

**Expected behavior**
It not throw, as it doesn't locally.

**Comment by xiaohaoxing** [comment]
Me too, my own crawler tool is also facing this problem, I'm working on it

**Comment by xiaohaoxing** [comment]
Could you please provide the minimum code that reproduces this problem?

**Comment by jo-sip** [comment]
> Could you please provide the minimum code that reproduces this problem?

Sure thing, here's my deployment code:

```
const apiHandler = new NodejsFunction(this, env("api-handler"), {
      architecture: Architecture.ARM_64,
      memorySize: 512,
      runtime: Runtime.NODEJS_20_X,
      timeout: Duration.seconds(20),
      entry: path.join(__dirname, "./lambda/api.handler.ts"),
      bundling: {
        minify: environment === "prod",
        target: "esnext",
      },
    });
```

```
export const handler = async (
  event: APIGatewayProxyEventV2,
): Promise<APIGatewayProxyResult> => {
  const youtube = new Client();
  console.log("v2");
  const video = await youtube.getVideo("dMvw7xx9HhQ");
  console.log(video);
  return {
    statusCode: 200,
    body: JSON.stringify({ message: "Hello from Lambda!" }),
  };
};
```

```
2024-11-15T18:13:11.638Z    ad0f6f85-9f76-4a06-ac79-b227475701d4    ERROR   Invoke Error    {"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'videoId')","stack":["TypeError: Cannot read properties of undefined (reading 'videoId')","    at BaseVideoParser.loadBaseVideo (/var/task/index.js:79129:44)","    at Video.load (/var/task/index.js:79289:43)","    at Video.load (/var/task/index.js:80595:15)","    at Client4.<anonymous> (/var/task/index.js:80753:113)","    at Generator.next (<anonymous>)","    at fulfilled (/var/task/index.js:80655:28)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]}
```

**Comment by jo-sip** [comment]
Is there a debugging method to log the http calls from the `Client`? I'm thinking that perhaps the call for the video is being blocked or erroring out, ending up being empty?

https://github.com/SuspiciousLookingOwl/youtubei/blob/1460ae806473127ac36b449f41fe78d553ab402e/src/youtube/Client/Client.ts#L121-L134

**Comment by SuspiciousLookingOwl** [comment]
seems like YouTube made some changes to the response data, this changes rolled up on some user / IP (my local PC loads the data just fine, but I'm facing similar error on my server), checking it

**Comment by xiaohaoxing** [comment]
Hi, I've working on this issue for a while and find the solution for getting video information #126 
But i didn't confirm that is it necessary to add `params` to `nextPromise` above, can you please check it? @SuspiciousLookingOwl  Thanks！

**Comment by shuntan** [comment]
I got same error and using proxy：

 /www/wwwroot/youtubei/node_modules/youtubei/dist/cjs/youtube/BaseVideo/BaseVideoParser.js:14
target.id = videoInfo.videoDetails.videoId;
^

TypeError: Cannot read properties of undefined (reading 'videoId')
at Function.loadBaseVideo (/www/wwwroot/youtubei/node_modules/youtubei/dist/cjs/youtube/BaseVideo/BaseVideoParser.js:14:44)
at Video.load (/www/wwwroot/youtubei/node_modules/youtubei/dist/cjs/youtube/BaseVideo/BaseVideo.js:21:43)
at Video.load (/www/wwwroot/youtubei/node_modules/youtubei/dist/cjs/youtube/Video/Video.js:30:15)
at Client.<anonymous> (/www/wwwroot/youtubei/node_modules/youtubei/dist/cjs/youtube/Client/Client.js:94:55)
at Generator.next (<anonymous>)
at fulfilled (/www/wwwroot/youtubei/node_modules/youtubei/dist/cjs/youtube/Client/Client.js:5:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by fdciabdul** [comment]
as far i know, youtube always flag suspicious IP, make sure you have to slow down or make random interval request, so your server IP doesn't get flag 'spam' by Youtube

**Comment by DoxrGitHub** [comment]
I found what file was erroring, I edited the build (sorry) and made it log the "raw" thing it got before it tried to get values from it and saw that the response was beautiful and in my case I would actually be fine with just having that data and parsing it myself (but obviously its not that easy)

So I don't think its an error due to YouTube returning a bad response, they probably changed how the response looks and yeah. Unless I'm not recognizing it's not returning the actual info.

**Comment by programming-with-ia** [comment]
@DoxrGitHub 
**How can you fix this**

i am working with nextjs it's working fine on server-side
but client-side causing the issue

**Comment by rafalzawadzki** [comment]
this can't be "fixed" with code, it's YT blocking your requests

you either figure out some proxy or just use something like [supadata](https://supadata.ai/youtube-transcript-api) instead

**Comment by programming-with-ia** [comment]
Hey @rafalzawadzki, 👋

I need video details like duration, likes, viewCount, etc. If you know any other solution, please let me know!

Thanks for your previous response! 🙌😊

**Comment by rafalzawadzki** [comment]
> Hey [@rafalzawadzki](https://github.com/rafalzawadzki), 👋
> 
> I need video details like duration, likes, viewCount, etc. If you know any other solution, please let me know!
> 
> Thanks for your previous response! 🙌😊

yup, see this: https://supadata.ai/documentation/youtube/video :)

**Comment by thomasperge** [comment]
Hey, go check out: https://github.com/thomasperge/youtube-scraping-transcription
