### ISSUE TITLE
'punycode' module error

### ISSUE THREAD

**Issue by MohitKashyapUK** [SuspiciousLookingOwl/youtubei#128]
(node:9400) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Promise { <pending> }
C:\Users\Mohit\Documents\GitHub\youtube-node\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:32
            videoCountText = (_k = metadataRow.metadataParts.find((m) => m.text.styleRuns)) === null || _k === void 0 ? void 0 : _k.text.content;
                                               ^

TypeError: Cannot read properties of undefined (reading 'metadataParts')
    at ChannelParser.loadChannel (C:\Users\Mohit\Documents\GitHub\youtube-node\node_modules\youtubei\dist\cjs\youtube\Channel\ChannelParser.js:32:48)
    at Channel.load (C:\Users\Mohit\Documents\GitHub\youtube-node\node_modules\youtubei\dist\cjs\youtube\Channel\Channel.js:20:39)
    at Client.<anonymous> (C:\Users\Mohit\Documents\GitHub\youtube-node\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:108:60)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Mohit\Documents\GitHub\youtube-node\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.12.0

**Comment by rafalzawadzki** [comment]
the title is misleading - this in fact is not a problem with punycode, but a bug related to this: https://github.com/SuspiciousLookingOwl/youtubei/issues/112 and this https://github.com/SuspiciousLookingOwl/youtubei/issues/132

**Comment by thomasperge** [comment]
Hey, go check out: https://github.com/thomasperge/youtube-scraping-transcription
