### ISSUE TITLE
[BUG] Client#search errors when no results exist

### ISSUE THREAD

**Issue by KinectTheUnknown** [SuspiciousLookingOwl/youtubei#3]
**Describe the bug**
When passing a query into `Client#search` that produces no results, the following error is thrown:
```
TypeError: Cannot read property 'continuationItemRenderer' of undefined
    at SearchResult.loadSearchResult (/Users/inquire_kinect/VSC/Repos/TommyBot/node_modules/.pnpm/youtubei@0.0.1-rc.10/node_modules/youtubei/dist/classes/SearchResult.js:107:19)
    at SearchResult.<anonymous> (/Users/inquire_kinect/VSC/Repos/TommyBot/node_modules/.pnpm/youtubei@0.0.1-rc.10/node_modules/youtubei/dist/classes/SearchResult.js:63:18)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/inquire_kinect/VSC/Repos/TommyBot/node_modules/.pnpm/youtubei@0.0.1-rc.10/node_modules/youtubei/dist/classes/SearchResult.js:11:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**To Reproduce**
```js
const YTI = require("youtubei")
const yt = new YTI.Client()

yt.search("ewiqur6iuwraflojksadbvasadfgshp2sr")
  .then(console.log, console.error)
```

**Expected behavior**
What should happen instead is that either an empty array or null should be returned.

**Comment by SuspiciousLookingOwl** [comment]
Thank you for reporting this!

It is indeed should return an empty array instead of throwing an error, will fix this soon.

**Comment by SuspiciousLookingOwl** [comment]
Please upgrade rc.12 😁

Plus you can also now check the estimated result count
```js
const result = await youtube.serach("...");

console.log(result.estimatedResults);
```
