### ISSUE TITLE
Some Channels throw error: "Cannot read property 'items' of undefined"

### ISSUE THREAD

**Issue by supertiger1234** [SuspiciousLookingOwl/youtubei#39]
**Describe the bug**
Some channels such as PewDiePie throw error.
```
(node:18860) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'items' of undefined
    at Channel.load (E:\WatchSquad\server\node_modules\youtubei\dist\classes\Channel.js:46:58)
    at Client.<anonymous> (E:\WatchSquad\server\node_modules\youtubei\dist\classes\Client.js:93:53)
    at Generator.next (<anonymous>)
    at fulfilled (E:\WatchSquad\server\node_modules\youtubei\dist\classes\Client.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
```js
// PewDiePie Channel ID is used.
client.getChannel("UC-lHJZR3Gqxm24_Vd_AJ5Yw").then(res => {
    console.log(res)
})
```

**Expected behavior**
Should return Channel object.

**Comment by SuspiciousLookingOwl** [comment]
Thanks for reporting this, will be fixed in next version
