### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by MikeDev96** [SuspiciousLookingOwl/youtubei#59]
Node version: 16.16.0

Searching for

`official audio lyrics Eliza Rose, Interplanetary Criminal B.O.T.A. (Baddest Of Them All) - Edit`

or

`official audio lyrics Solardo, Vintage Culture, LOWES Adidas & Pearls`

 results in the following error:

```
C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\VideoCompact\VideoCompactParser.js:16
            (detailedMetadataSnippets === null || detailedMetadataSnippets === void 0 ? void 0 : detailedMetadataSnippets[0].snippetText.runs.map((r) => r.text).join("")) || "";
                                                                                                                                              ^

TypeError: Cannot read properties of undefined (reading 'map')
    at Function.loadVideoCompact (C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\VideoCompact\VideoCompactParser.js:16:143)
    at VideoCompact.load (C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\VideoCompact\VideoCompact.js:32:49)
    at Function.parseSearchResult (C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\SearchResult\SearchResultParser.js:33:75)
    at Function.parseInitialSearchResult (C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\SearchResult\SearchResultParser.js:13:38)
    at SearchResult.<anonymous> (C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\SearchResult\SearchResult.js:65:88)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Trike\Documents\Projects\lucille-bot-dev\node_modules\youtubei\dist\cjs\classes\SearchResult\SearchResult.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by SuspiciousLookingOwl** [comment]
Should be fixed on next version, thanks for reporting.
