### ISSUE TITLE
getVideo() is failing with error

### ISSUE THREAD

**Issue by wddyousuf** [SuspiciousLookingOwl/youtubei#91]
**while calling for a video using getVideo(id) showing**

TypeError: Cannot read properties of undefined (reading 'defaultText')
    at BaseVideoParser.parseButtonRenderer (D:\laragon\www\youtubei-api\node_modules\youtubei\dist\cjs\youtube\BaseVideo\BaseVideoParser.js:84:58)
    at BaseVideoParser.loadBaseVideo (D:\laragon\www\youtubei-api\node_modules\youtubei\dist\cjs\youtube\BaseVideo\BaseVideoParser.js:30:64)
    at Video.load (D:\laragon\www\youtubei-api\node_modules\youtubei\dist\cjs\youtube\BaseVideo\BaseVideo.js:21:43)
    at Video.load (D:\laragon\www\youtubei-api\node_modules\youtubei\dist\cjs\youtube\Video\Video.js:30:15)
    at Client.<anonymous> (D:\laragon\www\youtubei-api\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:84:55)
    at Generator.next (<anonymous>)
    at fulfilled (D:\laragon\www\youtubei-api\node_modules\youtubei\dist\cjs\youtube\Client\Client.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**To Reproduce**
const youtube = new Client();
const video = await youtube.getVideo('e-nnyAmCUec');

**Screenshots**
![image](https://github.com/SuspiciousLookingOwl/youtubei/assets/75154914/ab6d29a1-51bf-4af4-b7b9-b2aed34486ab)

**Comment by wddyousuf** [comment]
Sorry I was using previous version. new version doesn't have the issue
